add X-Appoptics-Backfill-Token
appoptics/appoptics-api-ruby pull request #10
Opened 2019-02-18 14:11 UTC by kamilsluszniak

2019-02-20 14:09 UTC, mheffner reviewed
How about adding a test or two for this?

2019-02-21 08:34 UTC, kamilsluszniak commented
Tests added

2019-02-21 14:34 UTC, mheffner requested changes

2019-02-21 14:34 UTC, mheffner commented on lib/appoptics/metrics/client.rb
> +      def set_custom_headers(headers)
The other set operators in this class appear to use the `foo=` method form (see `api_endpoint=` and `custom_user_agent=`). Any reason you decided to go with a `set_` method instead? I think consistency here would be nice.

2019-02-21 14:34 UTC, mheffner commented on spec/unit/metrics_spec.rb
> +       expect(AppOptics::Metrics.client.custom_headers).to eq(headers)
Are there tests on the connection object that you could add to verify the headers are actually merged onto the connection?

2019-02-21 17:35 UTC, prettycoder commented
Sorry, this is not going to help with your problem. 
I took a quick peek at the tests and am wondering if newer Rubies should be added to .travis.yml
```
rvm:
  - 2.6.1
  - 2.5.3
```

2019-02-22 14:08 UTC, kamilsluszniak commented
@mheffner I have made changes as you suggested

2019-02-22 14:54 UTC, mheffner approved these changes

2019-02-22 15:29 UTC, kamilsluszniak commented
@mheffner I can't merge it, I don't have write access. Could you do that please? Or better, could you give me write access?

2019-02-22 16:01 UTC, mheffner commented
> @mheffner I can't merge it, I don't have write access. Could you do that please? Or better, could you give me write access?

I think the build is failing, can you take a look at that first?

2019-02-25 15:08 UTC, kamilsluszniak commented
@mheffner 46 tests are failing on master and 46 tests are failing on this branch, this is caused by prievious changes made by someone, and it seems that travis is not showing which commits caused the failing tests. I can fix the tests but it will take some time, because I'm not familiar with whole repository, just some fragments. I think that failing tests are caused by just some code updates without updating tests. Should I fix the tests broken by someone before merging this PR?

2019-02-25 15:26 UTC, mheffner commented
@kamilsluszniak I think it would be good to start with a clean test slate then. Can you start a new branch to get the tests passing first?

2019-02-26 20:28 UTC, prettycoder commented
@kamilsluszniak @cheempz asked me to see, if I can help with the tests.
I get 3 failing tests.
I found this commit https://github.com/appoptics/appoptics-api-ruby/commit/42407f2d6eecaec4dc143a467b847980e9f3e1ec that added the tests to make sure only `:source` or `:tags` (but not both) are used.
`:source` got removed in this commit https://github.com/appoptics/appoptics-api-ruby/commit/97a8eec and now the tests are failing. 
Reverting the 3 failing tests to what they were before that commit gets the tests to pass. 
I did not dig into the relation of `:source` to `:tags` to verify that the tests are testing the right thing.
Let me know if you would like me to look into that.

2019-02-26 20:36 UTC, chancefeick commented
> I did not dig into the relation of `:source` to `:tags` to verify that the tests are testing the right thing.

I believe we just incorrectly removed all `source` references when creating this repo. Reverting the tests works for me since raising the `InvalidParameters` exception is the desired behavior there. We do not want users to be able to set both `tags` and `source` arguments.

2019-03-05 15:20 UTC, kamilsluszniak commented
@chancefeick How are things going with fixing tests?

2019-03-06 08:26 UTC, merged